#!/bin/bash

GOOS=$(go env GOOS)

if [ ! -z "$R" ]; then
	echo Release build
	bdir="./bin/release/$GOOS"
	flags='-ldflags="-w -s"'
else
	bdir="./bin/debug/$GOOS"
	flags=''
fi
mkdir -p "$bdir"

oname="$bdir/%s"
[ "$GOOS" = "windows" ] && oname="$oname.exe"

build() {
	export SRCDIR=$(realpath "$1")
	export ONAME=$(basename "$1")
	export OFILE=$(printf "$oname" "$ONAME")
	
	if [ -f "$SRCDIR/main.go" ]; then
		echo "Building $ONAME"
		
		local dobuild=true
		
		if [ -x "$SRCDIR/build" ]; then
			echo "Running custom build..."
			"$SRCDIR/build" "$bdir" || dobuild=false
		fi
		
		[ "$dobuild" = true ] && go build -o "$OFILE" "$SRCDIR" || echo "Compilation failed [$?]"
	fi
}

[ $# = 0 ] && l=./* || l="$@"

for x in $l; do
	build $x
done
