#!/bin/bash

fmt() {
	sed -r 's/(^\s*|\s*$)//g; s/`/`+"`"+`/g' "$1" | tr -d '\n'
}

format='package main

var gladeMain=`%s`
'

printf "$format" \
	"$(fmt ./smmodtool/resources/main.glade)" \
	> ./smmodtool/resources.go

if [ "$GOOS" = windows ]; then
	CGO_ENABLED=1 \
	CC=x86_64-w64-mingw32-cc \
	GOARCH=amd64 \
	go build -ldflags '-H=windowsgui' -o "$OFILE" "$SRCDIR"
	
	exit 1 # don't build with main script
fi
